name: Publish
on:
  push:
    tags:
      - v*.*.*

  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    - uses: actions/checkout@v3  
    - name: Setup .NET 6
      uses: actions/setup-dotnet@2
      with:
        dotnet-version: |
        6.0.x
        5.0.x
        3.1.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
    - name: Install dependencies
      run: dotnet restore -s https://api.nuget.org/v3/index.json
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack -c Release -o tmp --no-restore --no-build
    - run: cd ../
    - name: publish nuget
      run: dotnet nuget push tmp\*.nupkg --skip-duplicate --no-symbols true -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json  